/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 14 17:47:50 GMT 2024
 */

package ir.ramtung.impl1;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DuplicateDocumentEx_ESTest extends DuplicateDocumentEx_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DuplicateDocumentEx duplicateDocumentEx0 = new DuplicateDocumentEx("");
  }
}
