/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 14 17:47:31 GMT 2024
 */

package ir.ramtung.impl1;

import org.evosuite.runtime.EvoAssertions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Magazine_ESTest extends Magazine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Magazine magazine0 = new Magazine("4`v)70r8q_m{'RtnW*", 1264, 1264);
      magazine0.number = 1264;
      magazine0.number = 1;
      int int0 = magazine0.penaltyFor(586);
      Assert.assertEquals(1172000, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Magazine magazine0 = new Magazine((String) null, 1484, 1172000);
      int int0 = magazine0.penaltyFor(0);
      Assert.assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Magazine magazine0 = null;
      try {
        magazine0 = new Magazine("_sqhD", 150, (-1322));
        Assert.fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Magazine with zero or negative number
         //
         EvoAssertions.verifyException("ir.ramtung.impl1.Magazine", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Magazine magazine0 = new Magazine("1", 1390, 1390);
      int int0 = magazine0.penaltyFor(2);
      Assert.assertEquals(6000, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Magazine magazine0 = new Magazine("4`v)70r8q_m{'RtnW*", 1264, 1264);
      try { 
        magazine0.penaltyFor(1172000);
        Assert.fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // The number of late days exceeds a thousand years.
         //
         EvoAssertions.verifyException("ir.ramtung.impl1.Magazine", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Magazine magazine0 = new Magazine((String) null, 1484, 1172000);
      int int0 = magazine0.penaltyFor((-2214));
      Assert.assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Magazine magazine0 = null;
      try {
        magazine0 = new Magazine("k=TIzBrXFeRz5", 1713, 0);
        Assert.fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Magazine with zero or negative number
         //
         EvoAssertions.verifyException("ir.ramtung.impl1.Magazine", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Magazine magazine0 = null;
      try {
        magazine0 = new Magazine((String) null, 0, 0);
        Assert.fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Magazine with zero or negative publication year
         //
         EvoAssertions.verifyException("ir.ramtung.impl1.Magazine", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Magazine magazine0 = new Magazine("4`v)70r8q_m{'RtnW*", 1264, 1264);
      int int0 = magazine0.loanDuration();
      Assert.assertEquals(2, int0);
  }
}
