/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 14 17:40:02 GMT 2024
 */

package ir.ramtung.impl1;

import org.evosuite.runtime.EvoAssertions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Reference_ESTest extends Reference_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Reference reference0 = new Reference((String) null);
      int int0 = reference0.penaltyFor(365000);
      Assert.assertEquals(1824937000, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Reference reference0 = new Reference("Documents with empty title are not allowed");
      int int0 = reference0.penaltyFor(0);
      Assert.assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Reference reference0 = new Reference((String) null);
      try { 
        reference0.penaltyFor(4617000);
        Assert.fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // The number of late days exceeds a thousand years.
         //
         EvoAssertions.verifyException("ir.ramtung.impl1.Reference", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Reference reference0 = new Reference("The number of late days exceeds a thousand years.");
      int int0 = reference0.penaltyFor(3);
      Assert.assertEquals(36000, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Reference reference0 = new Reference("Le\"q\"I5#");
      int int0 = reference0.penaltyFor((-469));
      Assert.assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Reference reference0 = new Reference((String) null);
      int int0 = reference0.penaltyFor(936);
      Assert.assertEquals(4617000, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Reference reference0 = new Reference("ir.ramtung.impl1.ExcessiveLateDaysException");
      int int0 = reference0.loanDuration();
      Assert.assertEquals(5, int0);
  }
}
