/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 14 18:12:23 GMT 2024
 */

package ir.ramtung.impl2;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.assertEquals;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Book_ESTest extends Book_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        Book book0 = new Book("", (-1698));
        int int0 = book0.calculatePenalty((-21));
        assertEquals(10, book0.getDay());
        assertEquals(3000, int0);
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        Book book0 = new Book("", (-1698));
        int int0 = book0.calculatePenalty(2000);
        assertEquals(2000, int0);
        assertEquals(10, book0.getDay());
    }

    @Test(timeout = 4000)
    public void test2() throws Throwable {
        Book book0 = new Book("", (-1698));
        int int0 = book0.calculatePenalty((-1698));
        assertEquals(2000, int0);
        assertEquals(10, book0.getDay());
    }
}
