/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 14 18:06:33 GMT 2024
 */

package ir.ramtung.impl2;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.assertEquals;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Reference_ESTest extends Reference_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Reference reference0 = new Reference("", (-1));
      int int0 = reference0.calculatePenalty((-1330));
      assertEquals(7000, int0);
      assertEquals(5, reference0.getDay());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Reference reference0 = new Reference("", 1066);
      int int0 = reference0.calculatePenalty(1066);
      assertEquals(5, reference0.getDay());
      assertEquals(5000, int0);
  }
}
