/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 14 18:14:03 GMT 2024
 */

package ir.ramtung.impl2;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.assertEquals;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Document_ESTest extends Document_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Reference reference0 = new Reference("", 1005);
      reference0.barrowBook();
      assertEquals(1004, reference0.getCopies());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Reference reference0 = new Reference("", 1005);
      int int0 = reference0.getCopies();
      assertEquals(1005, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Book book0 = new Book("", 10);
      book0.calculatePenalty(1005);
      assertEquals(10, book0.getCopies());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Book book0 = new Book("", 10);
      int int0 = book0.getDay();
      assertEquals(10, book0.getCopies());
      assertEquals(10, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Book book0 = new Book("", 10);
      book0.barrowBook();
      int int0 = book0.getDay();
      assertEquals(9, book0.getCopies());
      assertEquals(10, int0);
  }
}
