/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 14 18:10:47 GMT 2024
 */

package ir.ramtung.impl2;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.assertEquals;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Magazine_ESTest extends Magazine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Magazine magazine0 = new Magazine("t", (-2057), (-1918), (-2057));
      int int0 = magazine0.calculatePenalty((-1918));
      assertEquals(2, magazine0.getDay());
      assertEquals(2000, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Magazine magazine0 = new Magazine("{<", 3028, 1044, 1390);
      int int0 = magazine0.calculatePenalty(1044);
      assertEquals(3000, int0);
      assertEquals(2, magazine0.getDay());
  }
}
