/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 14 18:09:18 GMT 2024
 */

package ir.ramtung.impl2;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Prof_ESTest extends Prof_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Prof prof0 = new Prof((String) null);
      Magazine magazine0 = new Magazine((String) null, 5, (-1), 3);
      prof0.borrow(magazine0);
      prof0.borrow(magazine0);
      prof0.borrow(magazine0);
      prof0.borrow(magazine0);
      assertTrue(prof0.canBorrow());
      
      prof0.borrow(magazine0);
      prof0.borrow(magazine0);
      boolean boolean0 = prof0.canBorrow();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Prof prof0 = new Prof((String) null);
      boolean boolean0 = prof0.canBorrow();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Prof prof0 = new Prof((String) null);
      Magazine magazine0 = new Magazine((String) null, 5, (-1), 3);
      prof0.borrow(magazine0);
      prof0.borrow(magazine0);
      prof0.borrow(magazine0);
      prof0.borrow(magazine0);
      assertTrue(prof0.canBorrow());
      
      prof0.borrow(magazine0);
      boolean boolean0 = prof0.canBorrow();
      assertFalse(boolean0);
  }
}
