/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 14 18:14:38 GMT 2024
 */

package ir.ramtung.impl2;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.List;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Student_ESTest extends Student_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Student student0 = new Student("", "");
      Magazine magazine0 = new Magazine("", (-3495), 2, 2);
      student0.borrow(magazine0);
      assertTrue(student0.canBorrow());
      
      Book book0 = new Book("", 247);
      student0.borrow(book0);
      boolean boolean0 = student0.canBorrow();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Student student0 = new Student("", "");
      boolean boolean0 = student0.canBorrow();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Student student0 = new Student("", "");
      assertTrue(student0.canBorrow());
      
      Book book0 = new Book("", 1);
      Magazine magazine0 = new Magazine("J2R3/~x#D", 1, 1, 1);
      Reference reference0 = new Reference("", 1);
      List<Document> list0 = List.of((Document) book0, (Document) book0, (Document) book0, (Document) magazine0, (Document) magazine0, (Document) reference0, (Document) magazine0, (Document) magazine0, (Document) book0, (Document) magazine0);
      student0.docsBorrow = list0;
      boolean boolean0 = student0.canBorrow();
      assertFalse(boolean0);
  }
}
