/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 14 17:49:48 GMT 2024
 */

package ir.ramtung.impl1;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Book_ESTest extends Book_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Book book0 = new Book("kd+EX?fw*<V2");
      int int0 = book0.penaltyFor(10);
      Assert.assertEquals(23000, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Book book0 = new Book("kd+EX?fw*<V2");
      int int0 = book0.penaltyFor(14000);
      Assert.assertEquals(69951000, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Book book0 = new Book("kd+EX?fw*<V2");
      int int0 = book0.penaltyFor(7);
      Assert.assertEquals(14000, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Book book0 = new Book("kd+EX?fw*<V2");
      int int0 = book0.loanDuration();
      Assert.assertEquals(10, int0);
  }
}
