/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 14 17:50:27 GMT 2024
 */

package ir.ramtung.impl1;

import org.evosuite.runtime.EvoAssertions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Document_ESTest extends Document_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Reference reference0 = new Reference("]5}@9F9u");
      boolean boolean0 = reference0.isTitled("yk|vbP");
      Assert.assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Book book0 = new Book((String) null);
      String string0 = book0.getTitle();
      Assert.assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Reference reference0 = new Reference("]5}@9F9u");
      reference0.title = "?Dg)GzPP5isKh{";
      reference0.title = "";
      String string0 = reference0.getTitle();
      Assert.assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Book book0 = null;
      try {
        book0 = new Book("");
        Assert.fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Documents with empty title are not allowed
         //
         EvoAssertions.verifyException("ir.ramtung.impl1.Document", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Book book0 = new Book("]5}@9F9u");
      boolean boolean0 = book0.isTitled("]5}@9F9u");
      Assert.assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Reference reference0 = new Reference("]5}@9F9u");
      String string0 = reference0.getTitle();
      Assert.assertEquals("]5}@9F9u", string0);
  }
}
