/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 14 17:38:14 GMT 2024
 */

package ir.ramtung.impl1;

import org.evosuite.runtime.EvoAssertions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.List;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Library_ESTest extends Library_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Library library0 = new Library();
      library0.addReference((String) null, 1562);
      try { 
        library0.addReference((String) null, 1990);
        Assert.fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Document with the same title exists
         //
         EvoAssertions.verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Library library0 = new Library();
      library0.timePass(864);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Library library0 = new Library();
      library0.addProfMember("Cannot borrow more documents");
      int int0 = library0.getTotalPenalty("Cannot borrow more documents");
      Assert.assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Library library0 = new Library();
      List<String> list0 = library0.availableTitles();
      Assert.assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Library library0 = new Library();
      library0.addMagazine("Cannot borrow more documents", 2065, 494, 2516);
      try { 
        library0.borrow("Cannot borrow more documents", "Cannot borrow more documents");
        Assert.fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Cannot find member to borrow
         //
         EvoAssertions.verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Library library0 = new Library();
      library0.addReference((String) null, 1562);
      List<String> list0 = library0.availableTitles();
      Assert.assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Library library0 = new Library();
      library0.addBook("<=G2", 2516);
      library0.addMagazine("Cannot borrow more documents", 2065, 494, 2516);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Library library0 = new Library();
      library0.addProfMember("Cannot borrow more documents");
      library0.addMagazine("Cannot borrow more documents", 2065, 494, 2516);
      library0.borrow("Cannot borrow more documents", "Cannot borrow more documents");
      int int0 = library0.getTotalPenalty("Cannot borrow more documents");
      Assert.assertEquals(0, int0);
  }
}
