/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 14 17:51:45 GMT 2024
 */

package ir.ramtung.impl1;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Student_ESTest extends Student_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Student student0 = new Student("Empty student ID is not allowed", "Zk>61OlC_-LV++E=@");
      int int0 = student0.allowedToBorrow();
      Assert.assertEquals(2, int0);
  }
}
